// Copyright 2026 Scitrera LLC
// SPDX-License-Identifier: AGPL-3.0-only

package snapshot

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"sort"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/s3/transfermanager"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/s3/types"

	"github.com/scitrera/memorylayer-storage/casstore/s3util"
)

// S3Config carries the configuration for an S3-backed snapshot store.
// It works with AWS S3 and any S3-compatible service (RustFS, Cloudflare R2,
// Backblaze B2) via the optional Endpoint field.
//
// It is an alias for s3util.Config, the shared S3 client configuration; the
// alias keeps the long-standing snapshot.S3Config public name stable for
// external callers (e.g. blobgw's main) while the client-construction logic
// lives in one place.
type S3Config = s3util.Config

// S3Store is an S3-backed SnapshotStore. Object keys follow the layout:
//
//	<prefix>/<tenant>/<workspace>/<user>/<owner_key>/<version>/blob
//	<prefix>/<tenant>/<workspace>/<user>/<owner_key>/<version>/metadata.json
//
// Where empty workspace/user become "_" (consistent with LocalStore layout).
type S3Store struct {
	cfg      S3Config
	client   *s3.Client
	uploader *transfermanager.Client
}

// NewS3Store constructs an S3Store. The provided ctx is used only during
// construction to load the AWS config; subsequent calls supply their own ctx.
func NewS3Store(ctx context.Context, cfg S3Config) (*S3Store, error) {
	if cfg.Bucket == "" {
		return nil, errors.New("snapshot/s3: Bucket is required")
	}

	client, err := s3util.NewClient(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("snapshot/s3: %w", err)
	}
	uploader := transfermanager.New(client)

	return &S3Store{
		cfg:      cfg,
		client:   client,
		uploader: uploader,
	}, nil
}

// --- path helpers -----------------------------------------------------------

// objectKey builds the S3 object key for a blob or metadata object.
// name is "blob" or "metadata.json".
func (s *S3Store) objectKey(key SnapshotKey, version, name string) string {
	parts := []string{
		segmentOf(key.Tenant),
		segmentOf(key.Workspace),
		segmentOf(key.User),
		segmentOf(key.OwnerKey),
		version,
		name,
	}
	path := strings.Join(parts, "/")
	if s.cfg.Prefix != "" {
		return s.cfg.Prefix + "/" + path
	}
	return path
}

// versionPrefix builds the key prefix for all objects under a specific version.
func (s *S3Store) versionPrefix(key SnapshotKey, version string) string {
	base := s.objectKey(key, version, "")
	// objectKey ends with "/" + name; strip the trailing name separator to get
	// just the version prefix.
	return strings.TrimSuffix(base, "/")
}

// ownerPrefix builds the key prefix for all versions of a key.
func (s *S3Store) ownerPrefix(key SnapshotKey) string {
	parts := []string{
		segmentOf(key.Tenant),
		segmentOf(key.Workspace),
		segmentOf(key.User),
		segmentOf(key.OwnerKey),
	}
	path := strings.Join(parts, "/") + "/"
	if s.cfg.Prefix != "" {
		return s.cfg.Prefix + "/" + path
	}
	return path
}

// --- SnapshotStore implementation -------------------------------------------

// Put uploads the blob and metadata to S3. The version is generated by the
// store; SizeBytes is computed from the stream by the multipart uploader.
func (s *S3Store) Put(ctx context.Context, key SnapshotKey, meta SnapshotMetadata, r io.Reader) (SnapshotMetadata, error) {
	version := NewVersion()

	// Buffer so we can compute size and upload metadata after the blob.
	data, err := io.ReadAll(r)
	if err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/s3: read blob: %w", err)
	}

	// Upload blob via multipart manager.
	blobKey := s.objectKey(key, version, "blob")
	_, err = s.uploader.UploadObject(ctx, &transfermanager.UploadObjectInput{
		Bucket: aws.String(s.cfg.Bucket),
		Key:    aws.String(blobKey),
		Body:   bytes.NewReader(data),
	})
	if err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/s3: upload blob: %w", err)
	}

	// Stamp metadata and upload it.
	meta.Key = key
	meta.Version = version
	meta.SizeBytes = int64(len(data))
	if meta.CreatedAt.IsZero() {
		meta.CreatedAt = timeNow()
	}

	metaBytes, err := json.Marshal(meta)
	if err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/s3: marshal metadata: %w", err)
	}
	metaKey := s.objectKey(key, version, "metadata.json")
	_, err = s.uploader.UploadObject(ctx, &transfermanager.UploadObjectInput{
		Bucket: aws.String(s.cfg.Bucket),
		Key:    aws.String(metaKey),
		Body:   bytes.NewReader(metaBytes),
	})
	if err != nil {
		// Best-effort: attempt to delete the already-uploaded blob so we don't
		// leave orphaned blobs without metadata.
		_, _ = s.client.DeleteObject(ctx, &s3.DeleteObjectInput{
			Bucket: aws.String(s.cfg.Bucket),
			Key:    aws.String(blobKey),
		})
		return SnapshotMetadata{}, fmt.Errorf("snapshot/s3: upload metadata: %w", err)
	}

	slog.DebugContext(ctx, "snapshot/s3: put complete",
		"key", key, "version", version, "size", meta.SizeBytes)
	return meta, nil
}

// Get retrieves the blob and metadata for a specific version.
// Caller must Close the returned reader.
func (s *S3Store) Get(ctx context.Context, key SnapshotKey, version string) (io.ReadCloser, SnapshotMetadata, error) {
	// Fetch metadata first so we fail fast on a missing version.
	metaKey := s.objectKey(key, version, "metadata.json")
	metaOut, err := s.client.GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(s.cfg.Bucket),
		Key:    aws.String(metaKey),
	})
	if err != nil {
		if isS3NotFound(err) {
			return nil, SnapshotMetadata{}, ErrNoSnapshot
		}
		return nil, SnapshotMetadata{}, fmt.Errorf("snapshot/s3: get metadata: %w", err)
	}
	metaBytes, err := io.ReadAll(metaOut.Body)
	_ = metaOut.Body.Close()
	if err != nil {
		return nil, SnapshotMetadata{}, fmt.Errorf("snapshot/s3: read metadata: %w", err)
	}
	var meta SnapshotMetadata
	if err := json.Unmarshal(metaBytes, &meta); err != nil {
		return nil, SnapshotMetadata{}, fmt.Errorf("snapshot/s3: unmarshal metadata: %w", err)
	}

	// Fetch blob.
	blobKey := s.objectKey(key, version, "blob")
	blobOut, err := s.client.GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(s.cfg.Bucket),
		Key:    aws.String(blobKey),
	})
	if err != nil {
		if isS3NotFound(err) {
			return nil, SnapshotMetadata{}, ErrNoSnapshot
		}
		return nil, SnapshotMetadata{}, fmt.Errorf("snapshot/s3: get blob: %w", err)
	}

	slog.DebugContext(ctx, "snapshot/s3: get", "key", key, "version", version)
	return blobOut.Body, meta, nil
}

// GetLatest resolves the highest-version snapshot and delegates to Get.
// Returns ErrNoSnapshot when no versions exist.
func (s *S3Store) GetLatest(ctx context.Context, key SnapshotKey) (io.ReadCloser, SnapshotMetadata, error) {
	metas, err := s.List(ctx, key)
	if err != nil {
		return nil, SnapshotMetadata{}, err
	}
	if len(metas) == 0 {
		return nil, SnapshotMetadata{}, ErrNoSnapshot
	}
	// List returns newest first.
	return s.Get(ctx, key, metas[0].Version)
}

// GetLatestMetadata returns only the metadata for the highest-version snapshot
// without fetching the blob. It resolves the latest version via List (which
// reads only metadata.json objects) then returns that metadata directly,
// so the blob object is never requested.
func (s *S3Store) GetLatestMetadata(ctx context.Context, key SnapshotKey) (SnapshotMetadata, error) {
	metas, err := s.List(ctx, key)
	if err != nil {
		return SnapshotMetadata{}, err
	}
	if len(metas) == 0 {
		return SnapshotMetadata{}, ErrNoSnapshot
	}
	// List returns newest-first; index 0 is the latest version.
	slog.DebugContext(ctx, "snapshot/s3: get-latest-metadata", "key", key, "version", metas[0].Version)
	return metas[0], nil
}

// List returns metadata for all versions of key, newest first.
func (s *S3Store) List(ctx context.Context, key SnapshotKey) ([]SnapshotMetadata, error) {
	prefix := s.ownerPrefix(key)

	var metas []SnapshotMetadata
	paginator := s3.NewListObjectsV2Paginator(s.client, &s3.ListObjectsV2Input{
		Bucket: aws.String(s.cfg.Bucket),
		Prefix: aws.String(prefix),
	})
	for paginator.HasMorePages() {
		page, err := paginator.NextPage(ctx)
		if err != nil {
			return nil, fmt.Errorf("snapshot/s3: list objects: %w", err)
		}
		for _, obj := range page.Contents {
			k := aws.ToString(obj.Key)
			// We only want metadata.json objects so we read each version once.
			if !strings.HasSuffix(k, "/metadata.json") {
				continue
			}
			out, err := s.client.GetObject(ctx, &s3.GetObjectInput{
				Bucket: aws.String(s.cfg.Bucket),
				Key:    aws.String(k),
			})
			if err != nil {
				slog.WarnContext(ctx, "snapshot/s3: skipping unreadable metadata",
					"key", k, "err", err)
				continue
			}
			data, err := io.ReadAll(out.Body)
			_ = out.Body.Close()
			if err != nil {
				slog.WarnContext(ctx, "snapshot/s3: skipping unreadable metadata body",
					"key", k, "err", err)
				continue
			}
			var meta SnapshotMetadata
			if err := json.Unmarshal(data, &meta); err != nil {
				slog.WarnContext(ctx, "snapshot/s3: skipping malformed metadata",
					"key", k, "err", err)
				continue
			}
			metas = append(metas, meta)
		}
	}

	// Sort newest-first (descending version string = descending RFC3339Nano).
	sort.Slice(metas, func(i, j int) bool {
		return metas[i].Version > metas[j].Version
	})
	return metas, nil
}

// Walk yields every (key, version) tuple under the configured S3 prefix.
// Discovers snapshots by listing all metadata.json objects and reverse-
// parsing the path into (tenant, workspace, user, owner_key, version).
// Streams via the V2 paginator — memory is bounded by page size, not by
// the total snapshot count.
func (s *S3Store) Walk(ctx context.Context, yield func(SnapshotKey, string, SnapshotMetadata) error) error {
	listPrefix := ""
	if s.cfg.Prefix != "" {
		listPrefix = s.cfg.Prefix + "/"
	}
	paginator := s3.NewListObjectsV2Paginator(s.client, &s3.ListObjectsV2Input{
		Bucket: aws.String(s.cfg.Bucket),
		Prefix: aws.String(listPrefix),
	})
	for paginator.HasMorePages() {
		page, err := paginator.NextPage(ctx)
		if err != nil {
			return fmt.Errorf("snapshot/s3: walk list page: %w", err)
		}
		for _, obj := range page.Contents {
			k := aws.ToString(obj.Key)
			if !strings.HasSuffix(k, "/metadata.json") {
				continue
			}
			// Strip the cfg.Prefix and the trailing "/metadata.json"; what
			// remains is "<tenant>/<workspace>/<user>/<owner>/<version>".
			body := strings.TrimPrefix(k, listPrefix)
			body = strings.TrimSuffix(body, "/metadata.json")
			parts := strings.Split(body, "/")
			if len(parts) != 5 {
				slog.WarnContext(ctx, "snapshot/s3: walk: skipping object with unexpected layout",
					"key", k, "parts", len(parts))
				continue
			}
			out, err := s.client.GetObject(ctx, &s3.GetObjectInput{
				Bucket: aws.String(s.cfg.Bucket),
				Key:    aws.String(k),
			})
			if err != nil {
				slog.WarnContext(ctx, "snapshot/s3: walk: skipping unreadable metadata",
					"key", k, "err", err)
				continue
			}
			data, readErr := io.ReadAll(out.Body)
			_ = out.Body.Close()
			if readErr != nil {
				slog.WarnContext(ctx, "snapshot/s3: walk: skipping unreadable metadata body",
					"key", k, "err", readErr)
				continue
			}
			var meta SnapshotMetadata
			if err := json.Unmarshal(data, &meta); err != nil {
				slog.WarnContext(ctx, "snapshot/s3: walk: skipping malformed metadata",
					"key", k, "err", err)
				continue
			}
			sk := SnapshotKey{
				Tenant:    unsegmentOf(parts[0]),
				Workspace: unsegmentOf(parts[1]),
				User:      unsegmentOf(parts[2]),
				OwnerKey:  unsegmentOf(parts[3]),
			}
			if yErr := yield(sk, parts[4], meta); yErr != nil {
				return yErr
			}
		}
	}
	return nil
}

// unsegmentOf reverses segmentOf: the literal "_" sentinel becomes "".
// Other strings pass through. S3Store uses segmentOf rather than the
// full sanitize encoding (filesystem store), so there is no base64
// reverse to perform here.
func unsegmentOf(s string) string {
	if s == "_" {
		return ""
	}
	return s
}

// Delete removes all S3 objects under the given version prefix.
// Returns nil if already absent.
func (s *S3Store) Delete(ctx context.Context, key SnapshotKey, version string) error {
	prefix := s.versionPrefix(key, version) + "/"

	// Collect all keys under the version prefix.
	var toDelete []types.ObjectIdentifier
	paginator := s3.NewListObjectsV2Paginator(s.client, &s3.ListObjectsV2Input{
		Bucket: aws.String(s.cfg.Bucket),
		Prefix: aws.String(prefix),
	})
	for paginator.HasMorePages() {
		page, err := paginator.NextPage(ctx)
		if err != nil {
			return fmt.Errorf("snapshot/s3: list for delete: %w", err)
		}
		for _, obj := range page.Contents {
			toDelete = append(toDelete, types.ObjectIdentifier{
				Key: obj.Key,
			})
		}
	}

	if len(toDelete) == 0 {
		return nil // already absent
	}

	_, err := s.client.DeleteObjects(ctx, &s3.DeleteObjectsInput{
		Bucket: aws.String(s.cfg.Bucket),
		Delete: &types.Delete{
			Objects: toDelete,
			Quiet:   aws.Bool(true),
		},
	})
	if err != nil {
		return fmt.Errorf("snapshot/s3: delete objects: %w", err)
	}
	slog.DebugContext(ctx, "snapshot/s3: deleted", "key", key, "version", version, "objects", len(toDelete))
	return nil
}

// --- error helpers ----------------------------------------------------------

// isS3NotFound returns true for NoSuchKey and 404-equivalent S3 errors.
func isS3NotFound(err error) bool {
	var noSuchKey *types.NoSuchKey
	if errors.As(err, &noSuchKey) {
		return true
	}
	// Some S3-compatible stores return a generic "NotFound" error.
	var notFound *types.NotFound
	if errors.As(err, &notFound) {
		return true
	}
	// Fallback: check the error string for common not-found indicators.
	msg := err.Error()
	return strings.Contains(msg, "NoSuchKey") || strings.Contains(msg, "404")
}
