// Copyright 2026 Scitrera LLC
// SPDX-License-Identifier: AGPL-3.0-only

package snapshot

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// LocalStore is a filesystem-backed SnapshotStore. It is suitable for
// development and single-node deployments where S3 is not available.
//
// Layout under rootDir:
//
//	<rootDir>/<tenant-seg>/<workspace-seg>/<user-seg>/<owner-key-seg>/<version>/blob
//	<rootDir>/<tenant-seg>/<workspace-seg>/<user-seg>/<owner-key-seg>/<version>/metadata.json
//
// Where each segment is either the raw value or, when the value is empty, the
// literal "_". Characters that are unsafe in filenames are base64url-encoded.
type LocalStore struct {
	rootDir string
}

// NewLocalStore creates a LocalStore rooted at rootDir, creating the directory
// if it does not already exist.
func NewLocalStore(rootDir string) (*LocalStore, error) {
	if err := os.MkdirAll(rootDir, 0o700); err != nil {
		return nil, fmt.Errorf("snapshot/local: mkdir root %q: %w", rootDir, err)
	}
	return &LocalStore{rootDir: rootDir}, nil
}

// --- path helpers -----------------------------------------------------------

// sanitize converts a segment value into a filesystem-safe name.
// Empty strings become "_". Values that contain "/" or other path-separator
// characters are base64url-encoded (no padding) to prevent directory traversal
// and to keep the path depth constant.
func sanitize(s string) string {
	if s == "" {
		return "_"
	}
	// If the value contains any characters that would break filesystem paths
	// or confuse the fixed-depth layout, encode the whole segment.
	if strings.ContainsAny(s, "/\\:*?\"<>|\x00") {
		return base64.RawURLEncoding.EncodeToString([]byte(s))
	}
	return s
}

// keyPath returns the directory for the given (key, version) pair.
// When version is empty the owner_key directory is returned.
func (s *LocalStore) keyPath(key SnapshotKey, version string) string {
	parts := []string{
		s.rootDir,
		sanitize(key.Tenant),
		sanitize(key.Workspace),
		sanitize(key.User),
		sanitize(key.OwnerKey),
	}
	if version != "" {
		parts = append(parts, version)
	}
	return filepath.Join(parts...)
}

func blobPath(versionDir string) string { return filepath.Join(versionDir, "blob") }
func metaPath(versionDir string) string { return filepath.Join(versionDir, "metadata.json") }

// --- SnapshotStore implementation -------------------------------------------

// Put writes a new snapshot version. The version string is generated by the
// store; SizeBytes in the input meta is ignored and recomputed from the stream.
// The write is atomic: bytes go to a temp file first, then renamed into place.
// metadata.json is written last so a partially-written blob is never visible
// behind a complete metadata.
func (s *LocalStore) Put(ctx context.Context, key SnapshotKey, meta SnapshotMetadata, r io.Reader) (SnapshotMetadata, error) {
	version := NewVersion()
	versionDir := s.keyPath(key, version)

	if err := os.MkdirAll(versionDir, 0o700); err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: mkdir version dir: %w", err)
	}

	// Stream to a temp file in the same directory so rename is atomic on the
	// same filesystem.
	tmp, err := os.CreateTemp(versionDir, "blob-*.tmp")
	if err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: create temp blob: %w", err)
	}
	tmpName := tmp.Name()

	// Ensure temp file is cleaned up on any error path.
	success := false
	defer func() {
		if !success {
			_ = tmp.Close()
			_ = os.Remove(tmpName)
			_ = os.Remove(versionDir) // best-effort; may fail if non-empty
		}
	}()

	n, err := io.Copy(tmp, r)
	if err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: write blob: %w", err)
	}
	if err = tmp.Close(); err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: close temp blob: %w", err)
	}

	// Atomic rename into final position.
	finalBlob := blobPath(versionDir)
	if err = os.Rename(tmpName, finalBlob); err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: rename blob: %w", err)
	}

	// Stamp metadata and write it last.
	meta.Key = key
	meta.Version = version
	meta.SizeBytes = n
	if meta.CreatedAt.IsZero() {
		meta.CreatedAt = timeNow()
	}

	if err = writeMetadata(metaPath(versionDir), meta); err != nil {
		// Blob is written; remove it to leave a clean state.
		_ = os.Remove(finalBlob)
		_ = os.Remove(versionDir)
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: write metadata: %w", err)
	}

	success = true
	slog.DebugContext(ctx, "snapshot/local: put complete",
		"key", key, "version", version, "size", n)
	return meta, nil
}

// Get returns the blob reader and metadata for the given version.
// Caller must Close the returned reader.
func (s *LocalStore) Get(ctx context.Context, key SnapshotKey, version string) (io.ReadCloser, SnapshotMetadata, error) {
	versionDir := s.keyPath(key, version)
	meta, err := readMetadata(metaPath(versionDir))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, SnapshotMetadata{}, ErrNoSnapshot
		}
		return nil, SnapshotMetadata{}, fmt.Errorf("snapshot/local: read metadata: %w", err)
	}

	f, err := os.Open(blobPath(versionDir))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, SnapshotMetadata{}, ErrNoSnapshot
		}
		return nil, SnapshotMetadata{}, fmt.Errorf("snapshot/local: open blob: %w", err)
	}
	slog.DebugContext(ctx, "snapshot/local: get", "key", key, "version", version)
	return f, meta, nil
}

// GetLatest enumerates the owner_key directory and returns the blob and
// metadata for the lexicographically-highest version. Returns ErrNoSnapshot
// when no versions exist.
func (s *LocalStore) GetLatest(ctx context.Context, key SnapshotKey) (io.ReadCloser, SnapshotMetadata, error) {
	versions, err := s.listVersionDirs(key)
	if err != nil {
		return nil, SnapshotMetadata{}, err
	}
	if len(versions) == 0 {
		return nil, SnapshotMetadata{}, ErrNoSnapshot
	}
	// versions is sorted newest-first; pick the first.
	return s.Get(ctx, key, versions[0])
}

// GetLatestMetadata returns only the metadata for the highest-version snapshot
// without opening the blob. For Local storage this means reading just the
// metadata.json file under the latest version directory.
func (s *LocalStore) GetLatestMetadata(ctx context.Context, key SnapshotKey) (SnapshotMetadata, error) {
	versions, err := s.listVersionDirs(key)
	if err != nil {
		return SnapshotMetadata{}, err
	}
	if len(versions) == 0 {
		return SnapshotMetadata{}, ErrNoSnapshot
	}
	// versions is sorted newest-first; read only the metadata.json for index 0.
	versionDir := s.keyPath(key, versions[0])
	meta, err := readMetadata(metaPath(versionDir))
	if err != nil {
		if os.IsNotExist(err) {
			return SnapshotMetadata{}, ErrNoSnapshot
		}
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: read metadata for latest: %w", err)
	}
	slog.DebugContext(ctx, "snapshot/local: get-latest-metadata", "key", key, "version", versions[0])
	return meta, nil
}

// List returns metadata for all versions, newest first.
func (s *LocalStore) List(ctx context.Context, key SnapshotKey) ([]SnapshotMetadata, error) {
	versions, err := s.listVersionDirs(key)
	if err != nil {
		return nil, err
	}
	out := make([]SnapshotMetadata, 0, len(versions))
	for _, v := range versions {
		versionDir := s.keyPath(key, v)
		meta, err := readMetadata(metaPath(versionDir))
		if err != nil {
			slog.Warn("snapshot/local: skipping unreadable metadata",
				"key", key, "version", v, "err", err)
			continue
		}
		out = append(out, meta)
	}
	return out, nil
}

// putWithMeta writes a blob under an already-assigned version (stamped in
// meta.Version). Used by CacheStore to populate the local cache with the exact
// version that the upstream store assigned, avoiding a second version
// generation. SizeBytes is recomputed from the stream.
func (s *LocalStore) putWithMeta(ctx context.Context, meta SnapshotMetadata, r io.Reader) (SnapshotMetadata, error) {
	version := meta.Version
	key := meta.Key
	versionDir := s.keyPath(key, version)

	if err := os.MkdirAll(versionDir, 0o700); err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: mkdir version dir: %w", err)
	}

	tmp, err := os.CreateTemp(versionDir, "blob-*.tmp")
	if err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: create temp blob: %w", err)
	}
	tmpName := tmp.Name()

	success := false
	defer func() {
		if !success {
			_ = tmp.Close()
			_ = os.Remove(tmpName)
			_ = os.Remove(versionDir)
		}
	}()

	n, err := io.Copy(tmp, r)
	if err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: write blob: %w", err)
	}
	if err = tmp.Close(); err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: close temp blob: %w", err)
	}

	finalBlob := blobPath(versionDir)
	if err = os.Rename(tmpName, finalBlob); err != nil {
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: rename blob: %w", err)
	}

	meta.SizeBytes = n
	if meta.CreatedAt.IsZero() {
		meta.CreatedAt = timeNow()
	}

	if err = writeMetadata(metaPath(versionDir), meta); err != nil {
		_ = os.Remove(finalBlob)
		_ = os.Remove(versionDir)
		return SnapshotMetadata{}, fmt.Errorf("snapshot/local: write metadata: %w", err)
	}

	success = true
	slog.DebugContext(ctx, "snapshot/local: putWithMeta complete",
		"key", key, "version", version, "size", n)
	return meta, nil
}

// Walk yields every (key, version) tuple stored under rootDir. Walks the
// fixed-depth directory layout (tenant/workspace/user/owner_key/version);
// directories that don't fit the layout (depth mismatch, missing
// metadata.json) are silently skipped.
//
// Segment names are reverse-mapped from their on-disk form via the
// unsanitize helper — base64url-encoded segments (those originally
// containing path-unsafe chars) are decoded back to their canonical
// values so callers see logical keys, not filesystem-escaped ones.
func (s *LocalStore) Walk(ctx context.Context, yield func(SnapshotKey, string, SnapshotMetadata) error) error {
	return filepath.WalkDir(s.rootDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			// Tolerate transient errors on individual directories so a
			// permission glitch on one tenant doesn't kill the whole walk.
			slog.WarnContext(ctx, "snapshot/local: walk: skipping entry",
				"path", path, "err", err)
			return nil
		}
		if !d.IsDir() {
			return nil
		}
		rel, relErr := filepath.Rel(s.rootDir, path)
		if relErr != nil {
			return nil
		}
		if rel == "." {
			return nil
		}
		parts := strings.Split(filepath.ToSlash(rel), "/")
		if len(parts) != 5 {
			return nil // not a version-level directory; keep descending
		}
		// At depth 5 the layout is <tenant>/<workspace>/<user>/<owner>/<version>.
		metaPath := filepath.Join(path, "metadata.json")
		meta, mErr := readMetadata(metaPath)
		if mErr != nil {
			// Partial / corrupt directory — skip silently. Walk's contract is
			// "yield every readable snapshot", not "complain about bad ones".
			return nil
		}
		key := SnapshotKey{
			Tenant:    unsanitize(parts[0]),
			Workspace: unsanitize(parts[1]),
			User:      unsanitize(parts[2]),
			OwnerKey:  unsanitize(parts[3]),
		}
		version := parts[4]
		if yErr := yield(key, version, meta); yErr != nil {
			return yErr
		}
		return nil
	})
}

// unsanitize reverses the sanitize encoding: "_" → "", otherwise tries
// base64url-decoding the segment and uses the decoded form when the
// decoded bytes contain any of the path-unsafe characters that would
// have triggered the encoding originally. Falls back to the literal
// segment when the decode produces a value that wouldn't have been
// sanitized anyway — this avoids accidentally "decoding" a tenant name
// like "abcd" that happens to be valid base64.
func unsanitize(s string) string {
	if s == "_" {
		return ""
	}
	if decoded, err := base64.RawURLEncoding.DecodeString(s); err == nil {
		if strings.ContainsAny(string(decoded), "/\\:*?\"<>|\x00") {
			return string(decoded)
		}
	}
	return s
}

// Delete removes the version directory. Returns nil if already absent.
func (s *LocalStore) Delete(ctx context.Context, key SnapshotKey, version string) error {
	versionDir := s.keyPath(key, version)
	err := os.RemoveAll(versionDir)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("snapshot/local: delete version %q: %w", version, err)
	}
	slog.DebugContext(ctx, "snapshot/local: deleted", "key", key, "version", version)
	return nil
}

// --- internal helpers -------------------------------------------------------

// listVersionDirs returns version strings for all existing versions of key,
// sorted newest-first (descending lexicographic order).
func (s *LocalStore) listVersionDirs(key SnapshotKey) ([]string, error) {
	ownerDir := s.keyPath(key, "")
	entries, err := os.ReadDir(ownerDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("snapshot/local: list versions: %w", err)
	}
	var versions []string
	for _, e := range entries {
		if e.IsDir() {
			versions = append(versions, e.Name())
		}
	}
	// Sort descending so index 0 is the newest.
	sort.Sort(sort.Reverse(sort.StringSlice(versions)))
	return versions, nil
}

// writeMetadata serialises meta to the given path.
func writeMetadata(path string, meta SnapshotMetadata) error {
	data, err := json.Marshal(meta)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o600)
}

// readMetadata deserialises metadata from the given path.
func readMetadata(path string) (SnapshotMetadata, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return SnapshotMetadata{}, err
	}
	var meta SnapshotMetadata
	if err := json.Unmarshal(data, &meta); err != nil {
		return SnapshotMetadata{}, err
	}
	return meta, nil
}
